mobs:
  PLAYER:
    DEFAULT:
      base: 0.4994
      looting: 0
      texture: {0}
      name: "&7{0}'s Head"
      
  BAT:
    DEFAULT:
      base: 0.02
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/4cf1b3b3f539d2f63c172e94cacfaa391e8b385cdd633f3b991c74e44b28"
      name: "&7Bat Head"
      
  BLAZE:
    DEFAULT:
      base: 0.0001
      looting: 0.00005
      texture: "http://textures.minecraft.net/texture/b78ef2e4cf2c41a2d14bfde9caff10219f5b1bf5b35a49eb51c6467882cb5f0"
      name: "&7Blaze Head"
      
  CAVE_SPIDER:
    DEFAULT:
      base: 0.001
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/41645dfd77d09923107b3496e94eeb5c30329f97efc96ed76e226e98224"
      name: "&7Cave Spider Head"
      
  CHICKEN:
    DEFAULT:
      base: 0.005
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/1638469a599ceef7207537603248a9ab11ff591fd378bea4735b346a7fae893"
      name: "&7Chicken Head"
      
  COW:
    DEFAULT:
      base: 0.005
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/5d6c6eda942f7f5f71c3161c7306f4aed307d82895f9d2b07ab4525718edc5"
      name: "&7Cow Head"
  
  CREEPER:
    DEFAULT:
      base: 0.002
      looting: 0.001
      texture: 4
      name: "&7Creeper Head"
    CHARGED:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/f2ceb39dd4de24a7adfe291a3a0cfc7cf4f645de59b603fcfe06c6b5a06e26"
      name: "&7Charged Creeper Head"
  
  DONKEY:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/dfb6c3c052cf787d236a2915f8072b77c547497715d1d2f8cbc9d241d88a"
      name: "&7Donkey Head"
      
  ELDER_GUARDIAN:
    DEFAULT:
      base: 0.3
      looting: 0.05
      texture: "http://textures.minecraft.net/texture/1c797482a14bfcb877257cb2cff1b6e6a8b8413336ffb4c29a6139278b436b"
      name: "&7Elder Guardian Head"
      
  ENDERMAN:
    DEFAULT:
      base: 0.00002
      looting: 0.00001
      texture: "http://textures.minecraft.net/texture/7a59bb0a7a32965b3d90d8eafa899d1835f424509eadd4e6b709ada50b9cf"
      name: "&7Enderman Head"
      
  ENDER_DRAGON:
    DEFAULT:
      base: 1
      looting: 0
      texture: 5
      name: "&7Ender Dragon Head"
      
  EVOKER:
    DEFAULT:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/a00d3fff16c2dca59b9c58f096525c86971166dbae133b1b050e5ee716443"
      name: "&7Evoker Head"
      
  GHAST:
    DEFAULT:
      base: 0.05
      looting: 0.025
      texture: "http://textures.minecraft.net/texture/8b6a72138d69fbbd2fea3fa251cabd87152e4f1c97e5f986bf685571db3cc0"
      name: "&7Ghast Head"
      
  GUARDIAN:
    DEFAULT:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/dfb675cb5a7e3fd25e29da8258f24fc020b3fa950362b8bc8eb252e56e74"
      name: "&7Guardian Head"
      
  HORSE:
    BLACK:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/64b7fc5f7a9ddfdd1aa79317410fc1929f91bddf98585938a2a56199a633cc"
      name: "&7Black Horse Head"
    BROWN:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/8a5fabbcbc5481976fb938a519ead59eeee2a071df297384a8fe96788a9df5a6"
      name: "&7Brown Horse Head"
    CHESTNUT:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/b66b2b32d31539c7383d923bae4faaf65da6715cd526c35d2e4e6825da11fb"
      name: "&7Chestnut Horse Head"
    CREAMY:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/628d1ab4be1e28b7b461fdea46381ac363a7e5c3591c9e5d2683fbe1ec9fcd3"
      name: "&7Creamy Horse Head"
    DARK_BROWN:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/42eb967ab94fdd41a6325f1277d6dc019226e5cf34977eee69597fafcf5e"
      name: "&7Dark Brown Horse Head"
    GRAY:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/413813dd45ed0ef838448cf6f631c157c23f9650c5ae451e978a53383312fe"
      name: "&7Gray Horse Head"
    WHITE:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/60a2db2f1eb93e5978d2dc91a74df43d7b75d9ec0e694fd7f2a652fbd15"
      name: "&7White Horse Head"
  
  IRON_GOLEM:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/89091d79ea0f59ef7ef94d7bba6e5f17f2f7d4572c44f90f76c4819a714"
      name: "&7Iron Golem Head"
  
  LLAMA:
    BROWN:
      base: 0.04
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/c2b1ecff77ffe3b503c30a548eb23a1a08fa26fd67cdff389855d74921368"
      name: "&7Brown Llama Head"
    CREAMY:
      base: 0.04
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/4d67fd4bff293269cb908974dca83c33485e435ed5a8e1dbd6521c61687140"
      name: "&7Creamy Llama Head"
    GRAY:
      base: 0.04
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/cf24e56fd9ffd7133da6d1f3e2f455952b1da462686f753c597ee82299a"
      name: "&7Gray Llama Head"
    WHITE:
      base: 0.04
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/80277e6b3d9f7819efc7da4b42745f7ab9a63ba8f36d6b84a7a250c6d1a358eb"
      name: "&7White Llama Head"
      
  MAGMA_CUBE:
    DEFAULT:
      base: 0.005
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/38957d5023c937c4c41aa2412d43410bda23cf79a9f6ab36b76fef2d7c429"
      name: "&7Magma Cube Head"
      
  MUSHROOM_COW:
    DEFAULT:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/d0bc61b9757a7b83e03cd2507a2157913c2cf016e7c096a4d6cf1fe1b8db"
      name: "&7Mushroom Cow Head"
      
  MULE:
    DEFAULT:
      base: 0.1
      looting: 0.05
      texture: "http://textures.minecraft.net/texture/a0486a742e7dda0bae61ce2f55fa13527f1c3b334c57c034bb4cf132fb5f5f"
      name: "&7Mule Head"
      
  OCELOT:
    BLACK_CAT:
      base: 0.04
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/f2a662f2ae7debee65292c2bf42fbb09b97b2ffbdb270520c2db96e51d8945"
      name: "&7Black Cat Head"
    RED_CAT:
      base: 0.04
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/a755e7df04d18b31d63c17f4a7b4c73924bd6265da69e113eddd97516fc7"
      name: "&7Tabby Cat Head"
    SIAMESE_CAT:
      base: 0.04
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/ab881c39b3afdcc79f91fe5de3cdd015bc3353843f591f4d23cd3027de4e6"
      name: "&7Siamese Cat Head"
    WILD_OCELOT:
      base: 0.04
      looting: 0.02
      texture: "http://textures.minecraft.net/texture/5657cd5c2989ff97570fec4ddcdc6926a68a3393250c1be1f0b114a1db1"
      name: "&7Ocelot head"
  
  PIG:
    DEFAULT:
      base: 0.005
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/621668ef7cb79dd9c22ce3d1f3f4cb6e2559893b6df4a469514e667c16aa4"
      name: "&7Pig Head"
  
  POLAR_BEAR:
    DEFAULT:
      base: 0.1
      looting: 0.05
      texture: "http://textures.minecraft.net/texture/d46d23f04846369fa2a3702c10f759101af7bfe8419966429533cd81a11d2b"
      name: "&7Polar Bear Head"
  
  SHULKER:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/1e73832e272f8844c476846bc424a3432fb698c58e6ef2a9871c7d29aeea7"
      name: "&7Shulker Head"
  
  SLIME:
    DEFAULT:
      base: 0.0005
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/16ad20fc2d579be250d3db659c832da2b478a73a698b7ea10d18c9162e4d9b5"
      name: "&7Slime Head"
  
  SKELETON:
    DEFAULT:
      base: 0.002
      looting: 0.001
      texture: 0
      name: "&7Skeleton Head"
  
  SKELETON_HORSE:
    DEFAULT:
      base: 0.2
      looting: 0.05
      texture: "http://textures.minecraft.net/texture/47effce35132c86ff72bcae77dfbb1d22587e94df3cbc2570ed17cf8973a"
      name: "&7Skeleton Horse Head"
  
  SHEEP:
    BLACK:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/32652083f28ed1b61f9b965df1abf010f234681c21435951c67d88364749822"
      name: "&7Black Sheep Head"
    BLUE:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/d9ec22818d1fbfc8167fbe36728b28240e34e16469a2929d03fdf511bf2ca1"
      name: "&7Blue Sheep Head"
    BROWN:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/a55ad6e5db5692d87f51511f4e09b39ff9ccb3de7b4819a7378fce8553b8"
      name: "&7Brown Sheep Head"
    CYAN:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/46f6c7e7fd514ce0acc68593229e40fcc4352b841646e4f0ebcccb0ce23d16"
      name: "&7Cyan Sheep Head"
    GRAY:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/4287eb501391f275389f166ec9febea75ec4ae951b88b38cae87df7e24f4c"
      name: "&7Gray Sheep Head"
    GREEN:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/a017215c7f8db82040aa2c47298b66541c2eb5f7f93040a5d23d88f0687d4b34"
      name: "&7Green Sheep Head"
    LIGHT_BLUE:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/1c8a97a38856514a16413e2c99521289f4c5363dc82fc9b2834cfedac78b89"
      name: "&7Light Blue Sheep Head"
    LIME:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/92a2448f58a491332434e85c45d786d874397e830a3a7894e6d92699c42b30"
      name: "&7Lime Sheep Head"
    MAGENTA:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/1836565c7897d49a71bc18986d1ea6561321a0bbf711d41a56ce3bb2c217e7a"
      name: "&7Magenta Sheep Head"
    ORAGE:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/f098397a270b4c3d2b1e574b8cfd3cc4ea3409066cefe31ea993633c9d576"
      name: "&7Orange Sheep Head"
    PINK:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/2ac74a2b9b91452e56fa1dda5db81077856e49f27c6e2de1e841e5c95a6fc5ab"
      name: "&7Pink Sheep Head"
    PURPLE:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/ae52867afef38bb14a26d1426c8c0f116ad34761acd92e7aae2c819a0d55b85"
      name: "&7Purple Sheep Head"
    RED:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/839af477eb627815f723a5662556ec9dfcbab5d494d338bd214232f23e446"
      name: "&7Red Sheep Head"
    SILVER:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/ce1ac683993be35512e1be31d1f4f98e583edb1658a9e21192c9b23b5cccdc3"
      name: "&7Silver Sheep Head"
    WHITE:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/f31f9ccc6b3e32ecf13b8a11ac29cd33d18c95fc73db8a66c5d657ccb8be70"
      name: "&7Sheep Head"
    YELLOW:
      base: 0.0175
      looting: 0.0025
      texture: "http://textures.minecraft.net/texture/26a4112df1e4bce2a5e28417f3aaff79cd66e885c3724554102cef8eb8"
      name: "&7Yellow Sheep Head"
    JEB:
      base: 0.1
      looting: 0.05
      texture: "http://textures.minecraft.net/texture/6c4cbf2dac42de3b2cbfd0aa1dc40363b6d3d5b5736b2a788c05d1b4abb19e7"
      name: "&7Jeb Sheep Head"
    
  SPIDER:
    DEFAULT:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/cd541541daaff50896cd258bdbdd4cf80c3ba816735726078bfe393927e57f1"
      name: "&7Spider Head"
  
  SQUID:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/01433be242366af126da434b8735df1eb5b3cb2cede39145974e9c483607bac"
      name: "&7Squid Head"
      
  SNOWMAN:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/1fdfd1f7538c040258be7a91446da89ed845cc5ef728eb5e690543378fcf4"
      name: "&7Snowman Head"
      
  VEX:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/5e7330c7d5cd8a0a55ab9e95321535ac7ae30fe837c37ea9e53bea7ba2de86b"
      name: "&7Vex Head"

  VINDICATOR:
    DEFAULT:
      base: 0.1
      looting: 0.05
      texture: "http://textures.minecraft.net/texture/a00d3fff16c2dca59b9c58f096525c86971166dbae133b1b050e5ee716443"
      name: "&7Vindicator Head"
 
  WOLF:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/e95cbb4f75ea87617f2f713c6d49dac3209ba1bd4b9369654b1459ea15317"
      name: "&7Wolf Head"
  
  VILLAGER:
    DEFAULT:
      base: 0.005
      looting: 0.005
      texture: "http://textures.minecraft.net/texture/822d8e751c8f2fd4c8942c44bdb2f5ca4d8ae8e575ed3eb34c18a86e93b"
      name: "&7Villager Head"
  
  PIG_ZOMBIE:
    DEFAULT: 
      base: 0.001
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/74e9c6e98582ffd8ff8feb3322cd1849c43fb16b158abb11ca7b42eda7743eb"
      name: "&7Zombie Pigman Head"
  
  ENDERMITE:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/84aaffa4c09e2eafb85d3522122db0aa45874bea4e3f5e7566b4d166c7df8"
      name: "&7Endermite Head"
      
  HUSK:
    DEFAULT: 
      base: 0.03
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/7770681d1a255fb4f754793aa055b220441cdab9e1141dfa5237b49931d9b91c"
      name: "&7Husk Head"
      
  RABBIT:
    BLACK:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/72c58116a147d1a9a26269224a8be184fe8e5f3f3df9b61751369ad87382ec9"
      name: "&7Black Rabbit Head"
    BLACK_AND_WHITE:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/cb8cff4b15b8ca37e25750f345718f289cb22c5b3ad22627a71223faccc"
      name: "&7Black and White Rabbit Head"
    BROWN:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/7d1169b2694a6aba826360992365bcda5a10c89a3aa2b48c438531dd8685c3a7"
      name: "&7Brown Rabbit Head"
    GOLD:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/c977a3266bf3b9eaf17e5a02ea5fbb46801159863dd288b93e6c12c9cb"
      name: "&7Gold Rabbit Head"
    SALT_AND_PEPPER:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/ffecc6b5e6ea5ced74c46e7627be3f0826327fba26386c6cc7863372e9bc"
      name: "&7Salt and Pepper Rabbit Head"
    THE_KILLER_BUNNY:
      base: 0.02
      looting: 0.01
      texture: ""
      name: "&7The Killer Bunny Head"
    TOAST:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/32fc3b74666545f2d41bc2b5340e1df69dd25e2a7e2b34efd1a95311a7d6c"
      name: "&7Toast Rabbit Head"
    WHITE:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/9542d7160987148a5d8e20e469bd9b3c2a3946c7fb5923f55b9beae99185f"
      name: "&7White Rabbit Head"
    
  SILVERFISH:
    DEFAULT:
      base: 0.02
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/da91dab8391af5fda54acd2c0b18fbd819b865e1a8f1d623813fa761e924540"
      name: "&7Silverfish Head"
      
  STRAY:
    DEFAULT:
      base: 0.05
      looting: 0.05
      texture: "http://textures.minecraft.net/texture/78ddf76e555dd5c4aa8a0a5fc584520cd63d489c253de969f7f22f85a9a2d56"
      name: "&7Stray Head"
  
  WITCH:
    DEFAULT:
      base: 0.002
      looting: 0.001
      texture: "http://textures.minecraft.net/texture/89e8b5f15a9b29a1e389c95218fd3795f32872e5aee9464a76495c527d2245"
      name: "&7Witch Head"
  
  PARROT:
    BLUE:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/aca580b051c63be29da545a9aa7ff7e136df77a81c67dc1ee9e6170c14fb310"
      name: "&7Blue Parrot Head"
    CYAN:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/2b94f236c4a642eb2bcdc3589b9c3c4a0b5bd5df9cd5d68f37f8c83f8e3f1"
      name: "&7Cyan Parrot Head"
    GRAY:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/3d6f4a21e0d62af824f8708ac63410f1a01bbb41d7f4a702d9469c6113222"
      name: "&7Gray Parrot Head"
    GREEN:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/ab9a36c5589f3a2e59c1caa9b3b88fada76732bdb4a7926388a8c088bbbcb"
      name: "&7Green Parrot Head"
    RED:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/a4ba8d66fecb1992e94b8687d6ab4a5320ab7594ac194a2615ed4df818edbc3"
      name: "&7Red Parrot Head"
      
  ZOMBIE:
    DEFAULT:
      base: 0.002
      looting: 0.001
      texture: 2
      name: "&7Zombie Head"
      
  ZOMBIE_VILLAGER:
    BLACKSMITH:
      base: 0.025
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/a16155fcf366cf4e06ce5dffc48ca54e8ea48dfe525358b612dc44fd432"
      name: "&7Blacksmith Zombie Villager Head"
    BUTCHER:
      base: 0.025
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/961f19ffd8ae425792c4b181756adff8d48174aeef58a0f327a28c742c72442"
      name: "&7Butcher Zombie Villager Head"
    FARMER:
      base: 0.025
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/cff0482fd32fab2ce9f5fa2e2d9b4dc7561da422152c99fc804b9139caf256b"
      name: "&7Farmer Zombie Villager Head"
    HUSK:
      base: 0.025
      looting: 0.01
      texture: ""
      name: "&7Husk Zombie Villager Head"
    LIBRARIAN:
      base: 0.025
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/44f08ebd4e25cda3ade45b863378ad377f18c510db4d28e82bb24451439b3734"
      name: "&7Librarian Zombie Villager Head"
    NITWIT:
      base: 0.025
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/37e838ccc26776a217c678386f6a65791fe8cdab8ce9ca4ac6b28397a4d81c22"
      name: "&7Nitwit Zombie Villager Head"
    NORMAL:
      base: 0.025
      looting: 0.01
      texture: ""
      name: "&7Normal Zombie Villager Head"
    PRIEST:
      base: 0.025
      looting: 0.01
      texture: "http://textures.minecraft.net/texture/528c2bad5389cb3592b565b3c47ecc189e0542a87835028d6148bbe3345645"
      name: "&7Priest Zombie Villager Head"
    
  ZOMBIE_HORSE:
    DEFAULT:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/d22950f2d3efddb18de86f8f55ac518dce73f12a6e0f8636d551d8eb480ceec"
      name: "&7Zombie Horse Head"
    
  WITHER:
    DEFAULT:
      base: 1
      looting: 0
      texture: "http://textures.minecraft.net/texture/3e4f49535a276aacc4dc84133bfe81be5f2a4799a4c04d9a4ddb72d819ec2b2b"
      name: "&7Wither Boss Head"

fish:
  enabled: true
  0:
    base: 0.0008
    texture: "http://textures.minecraft.net/texture/6f99b580d45a784e7a964e7d3b1f97cece74911173bd21c1d7c56acdc385ed5"
    name: "&7Fish Head"
  1:
    base: 0.0006
    texture: "http://textures.minecraft.net/texture/adfc57d09059e4799fa92c15e28512bcfaa1315577fe3a27aed389e4f752289a"
    name: "&7Salmon Head"
  2:
    base: 0.0002
    texture: "http://textures.minecraft.net/texture/36d149e4d499929672e2768949e6477959c21e65254613b327b538df1e4df"
    name: "&7Clownfish Head"
  3:
    base: 0.0004
    texture: "http://textures.minecraft.net/texture/a9559388993fe782f67bd58d98c4df56bcd430edcb2f66ef5777a73c27de3"
    name: "&7Pufferfish Head"
    